# Android & Gradle Configuration
android.useAndroidX=true
android.enableJetifier=false
android.disallowKotlinSourceSets=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64